### PR TITLE
Fix merge issues

### PR DESCRIPTION
**Pull request by SouthEndMusic**

### CODE REVIEW

**Comment by SouthEndMusic** [comment]
I don't know what to do about the Downgrade problems.

**Comment by sathvikbhagavan** [comment]
Try making compat of Test to be "1.10" instead of "1"

**Comment by SouthEndMusic** [comment]
There are some weird errors still.

**Comment by sathvikbhagavan** [comment]
That's most likely from Unitful, `_rangestyle` might not be defined in v1.0.0. Can you bump its compat to the latest one?

**Review by sathvikbhagavan — APPROVED** [review]

**Review by ChrisRackauckas — APPROVED** [review]

**Pull request merged**
