### PR TITLE
typos CI

### PR DESCRIPTION
**Pull request by ArnoStrouwen**

### CODE REVIEW

**Comment by sathvikbhagavan** [comment]
Does this check typos for docs as well?

**Comment by ArnoStrouwen** [comment]
Yes. It is just less likely to find them there, since I already went over those manually before.

**Comment by ChrisRackauckas** [comment]
What's the reason this one didn't get Aqua?

**Comment by ChrisRackauckas** [comment]
What package uses TreeViews? I thought it was removed awhile back?

**Comment by ArnoStrouwen** [comment]
I think it is https://github.com/SciML/MultiScaleArrays.jl/pull/83
and I also got the same error at Symbolics, but I did not confirm it was TreeViews that caused it.

**Comment by ChrisRackauckas** [comment]
We should remove all overloads of that. It only applies to Juno/Atom which is long gone now.

**Comment by ArnoStrouwen** [comment]
https://github.com/JuliaSymbolics/Symbolics.jl/blob/master/Project.toml#L39

**Pull request merged**
