### PR TITLE
CubicSplines: Add AbstractMatrix support

### PR DESCRIPTION
**Pull request by ashutosh-b-b**
## Checklist

- [x] Appropriate tests were added
- [x] Any code changes were done in a way that does not break public API
- [x] All documentation related to code changes were updated
- [x] The new code follows the
  [contributor guidelines](https://github.com/SciML/.github/blob/master/CONTRIBUTING.md), in particular the [SciML Style Guide](https://github.com/SciML/SciMLStyle) and
  [COLPRAC](https://github.com/SciML/COLPRAC).
- [x] Any new documentation only uses public API

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Why is this needed instead of the vector of vector form?

**Comment by sathvikbhagavan** [comment]
I think we should have both forms. Its also part of fixing https://github.com/SciML/DataInterpolations.jl/issues/206

**Comment by ashutosh-b-b** [comment]
> Why is this needed instead of the vector of vector form?

We can extend this to higher dimensional matrix. That is of course dependent on, whether we need that in DataInterpolations.jl

**Comment by ChrisRackauckas** [comment]
I see, yes we should support fully then.

**Comment by ashutosh-b-b** [comment]
Generalized this to AbstractArray and added tests for 3d arrays as well.

**Comment by sathvikbhagavan** [comment]
Can you rebase on master?

**Review by sathvikbhagavan — APPROVED** [review]
LGTM! A rebase and should be good to merge!

**Review by ChrisRackauckas — APPROVED** [review]

**Pull request merged**
